import Head from 'next/head'
import Image from 'next/image'

export default function Wc22() {
    return (
      <div>
        <Head>
          <title>Aliio Inc.</title>
          <meta name="description" content="Generated by Aliio" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png"/>
          <link rel="manifest" href="favicons/site.webmanifest"/>
          <link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#5bbad5"/>
          <meta name="msapplication-TileColor" content="#da532c"/>
          <meta name="theme-color" content="#ffffff"/>
          <meta name="facebook-domain-verification" content="k7653q8k5eoevfxnls44aeafvb8pun" />
        </Head>
  
        <main>
          <h1>
            Welcome to <a href="https://aliio.tech">Aliio</a>
          </h1>
          <div>
  
          </div>
        </main>
  
        <footer>
  
          <p><br></br>Powered by</p>
  
          <span>
            <a
              href="https://aliio.tech"
              target="_blank"
              rel="noopener noreferrer"
            ><Image src="/Aliio_official.png" alt="Aliio Official Logo" width={64} height={64} />
            </a>
          </span>
  
        </footer>
      </div>
      
    )
  }
  